name: shopzy
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

flutter_intl:
  main_locale: en
  enabled: true

dependencies:
  cached_network_image: ^3.4.1
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  either_dart: ^1.0.0
  envied: ^1.1.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_form_builder: ^10.0.1
  flutter_localizations:
    sdk: flutter
  flutter_loggy: ^2.0.3
  flutter_loggy_dio: ^3.1.0
  fluttertoast: ^8.2.12
  form_builder_validators: ^11.1.2
  go_router: ^15.2.0
  google_sign_in: ^6.3.0
  hooks_riverpod: ^2.6.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  loggy: ^2.0.3
  package_info_plus: ^8.3.0
  q_architecture: ^1.0.5
  retrofit: ^4.4.2
  sentry_flutter: ^8.14.2
  sign_in_with_apple: ^6.1.4
  sqflite: ^2.4.2
  supabase_auth_ui: ^0.5.5
  supabase_flutter: ^2.9.1

dev_dependencies:
  envied_generator: ^1.1.1
  build_runner: ^2.5.0
  custom_lint: ^0.7.5
  flutter_flavorizr: ^2.4.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.10
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  pyramid_lint: ^2.1.0
  retrofit_generator: ^9.2.0
  riverpod_lint: ^2.6.5

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/gifs/
